### ISSUE TITLE
Defining several koubachi devices in config yaml

### ISSUE THREAD

**Issue by polpas** [koalatux/koubachi-pyserver#21]
May you please give me an example of how to define several koubachi devices?

**Comment by koalatux** [comment]
If you received multiple configurations separately, then you can put them together in a single yaml file as shown in this example. Note: There are different versions of sensors, some need more calibration data than others.

```yaml
devices:
  000666000001:
    calibration_parameters:
      LM94022_TEMPERATURE_OFFSET: -4.81502287056831
      LM94022_VOLTAGE: 0.934495
      REFERENCE_TEMPERATURE: 23.121
      RN171_SMU_DC_OFFSET: 0.000174
      RN171_SMU_GAIN: 1.06070711893369
      RN171_SMU_REFERENCE_VOLTAGE_EXTERNAL: 0.295478
      RN171_SMU_REFERENCE_VOLTAGE_INTERNAL: 0.278741
      SFH3710_DC_OFFSET_CORRECTION: -0.000107
      SOIL_MOISTURE_DISCONTINUITY: 8903.44
      SOIL_MOISTURE_MIN: 3379.0
    key: 0123456789abcdef0123456789abcd01
  000666000002:
    calibration_parameters:
      LM94022_TEMPERATURE_OFFSET: -4.2034784621451
      LM94022_VOLTAGE: 0.931545
      REFERENCE_TEMPERATURE: 23.05
      RN171_SMU_DC_OFFSET: 0.000471
      RN171_SMU_GAIN: 1.06458338566656
      RN171_SMU_REFERENCE_VOLTAGE_EXTERNAL: 0.29666
      RN171_SMU_REFERENCE_VOLTAGE_INTERNAL: 0.279134
      SFH3710_DC_OFFSET_CORRECTION: 0.000174
      SOIL_MOISTURE_DISCONTINUITY: 11201.19
      SOIL_MOISTURE_MIN: 3360.0
    key: 0123456789abcdef0123456789abcd02
  000666000003:
    calibration_parameters:
      SOIL_MOISTURE_DISCONTINUITY: 10493.0
      SOIL_MOISTURE_MIN: 3346.0
    key: 0123456789abcdef0123456789abcd03
  000666000004:
    calibration_parameters:
      SOIL_MOISTURE_DISCONTINUITY: 10199.28
      SOIL_MOISTURE_MIN: 3329.0
    key: 0123456789abcdef0123456789abcd04
```
